### ISSUE TITLE
question about how to set data Parallelism 

### ISSUE THREAD

**Issue by Lechatelia** [microsoft/tutel#52]
Thanks for your contributions. Tutel is definitely a great work!
But I have difficulty applying this Tutel to a new framework.
If I have 8GPUs, And I want to set the number of experts to 4 while there are 2 local experts on a device (GPU).
Thus the GPUs will be divided into 4 groups, which each has 2 GPUs and contain 4 experts.
I think the GPU0, GPU2, GPU4, and  GPU6 have the experts with the same parameters.
How can I implement this setting?

**Comment by Lechatelia** [comment]
Maybe I could this can be implemented with deepspeed.

**Comment by ghostplant** [comment]
Hi, thanks for your question. I'd like to confirm what you request: do you need the setting that uses 8 GPU to support 4 experts so that on average, each expert is stored on 2 GPUs?

**Comment by Lechatelia** [comment]
Thanks for your reply. This is indeed what I require.
Now I have known how to do this with deepspeed. But I still have no idea about how to implement this with tutel only.

**Comment by ghostplant** [comment]
@Lechatelia The existing version yet doesn't include this feature when |GPU| > |Experts|. Please see this PR which will be merged once it passes regression tests: https://github.com/microsoft/tutel/pull/53/files, and it will support what you need by configuring: `experts = {'type': 'ffn', 'count_per_node': 0.5, ..}` which means each GPU will hold a half slice of an expert. If you concern about the precision of float value when it is large, you can also replace `0.5` with `-2` which donates `1 / 2`.

Note that we still see some optimization potential for the case |GPU| > |Experts| and it is yet not included in this PR.
We'll make it up soon after we have more evaluation about that.

**Comment by Lechatelia** [comment]
Thanks a lot for your help.
 I have another question. what should I do If 2 GPUs that hold the same expert constitute a data parallel process group, where each GPU will hold an entire expert.

**Comment by ghostplant** [comment]
I am curious about why you need that since it is more memory consuming.

I think this is a usage question about how you schedule group communicators with `torch.distributed`. Tutel's moe layer allows you specific custom-scheduled group communicators.

Do you mean by the following format?
```
GPU0 (Expert-0 Full)  GPU1 (Expert-1 Full) GPU2 (Expert-2 Full)  GPU3 (Expert-3 Full)
GPU4 (Expert-0 Full)  GPU5 (Expert-1 Full) GPU6 (Expert-2 Full)  GPU7 (Expert-3 Full)
```

**Comment by Lechatelia** [comment]
Yeah,  This is just what I want to do.
I think there will be more data (higher batch size) to train an expert in this format.
Maybe I got this wrong.
Thanks for your help again.

**Comment by ghostplant** [comment]
You may have interests in this example: https://github.com/ghostplant/tutel/blob/shared_expert/tutel/examples/helloworld_data_model.py

**Comment by Lechatelia** [comment]
Thank you! 
I think I have figured out how to do this with your help ~ _ ~

**Comment by ghostplant** [comment]
@Lechatelia  In v0.1.5, using data parallelism mode you request is much simplified, and there is no any programming differences with other MoE normal cases, e.g. You no longer need to create custom group and concern which params to communicate on data_group/model_group or global group.

You just need to set `count_per_node` = -4 for you case which means every adjacent 4 GPUs will maintain one expert. Each GPU will hold a unique slice of an expert params, and you don't need further all_reduce them on the `parallel_env.model_group`. The original example `helloworld_data_model.py` have been replaced by a new simpler example `helloworld_sharded_experts.py` for your reference.

**Comment by MiZhenxing** [comment]
Hi, @[ghostplant](https://github.com/ghostplant), 

Thank you for your excellent repo. I have a question about setting only distributed data parallel mode using tutel. For example, I want to train a model with **total** 16 experts on 2 GPUs. The model size is acceptable so I want each GPU hold the whole parameters of the 16 experts. I don't want 8 experts in each gpu. I just want each GPU to feed different data into the model. Such training mode is similar to the original distributed data parallel of PyTorch. However, I could not figure out how to set the arguments in tutel. I find in your code the `global_expert_count` is normally computed as `num_local_experts * world_size`, that is `num_local_experts * gpu_number`. If I set `num_local_experts` as 16 / 2 = 8, there will be a model parallel. So could you give me some hints about how to set the arguments so that I could use only distributed data parallel? 

Thank you very much.
Zhenxing Mi

**Comment by ghostplant** [comment]
@MiZhenxing To MoE parameters, data parallelism should be the worst choice. If you insist on using this inefficient approach. You need:
```py
from tutel import net
single_data_group = net.create_groups_from_world(group_count=1).data_group

self._moe_layer = tutel_moe.moe_layer(
            gate_type = {'type': 'top', 'k': top_value, 'fp32_gate': args.fp32_gate},
            experts = {'type': 'ffn', 'count_per_node': num_local_experts, 'hidden_size_per_expert': hidden_size, 'activation_fn': lambda x: F.relu(x)},
            model_dim = model_dim,
            seeds = (1, dist_rank + 1, 1),
            a2a_ffn_overlap_degree = a2a_ffn_overlap_degree,
            parallel_type = args.parallel_type,
-            scan_expert_func = lambda name, param: setattr(param, 'skip_allreduce', True),
+           group = single_data_group,
        )
```

Comparing with moe_layer creation in helloworld.py, you need to remove `scan_expert_func` argument and add `group` argument.

**Comment by MiZhenxing** [comment]
Hi, @[ghostplant](https://github.com/ghostplant), thank you very much for your help. I will test on these setting.

**Comment by luuck** [comment]
Hello, I am using DeepSpeed to implement data parallelism + pipeline parallelism + tutel moe. My node has 6 GPUs, and I started training with the command: 
                  python -m torch.distributed.launch --nproc_per_node=6 train.py
    The model was split into 2 parts, so the data parallelism is 3 and the model parallelism is 2.
  
 (1) If I set num_local_experts to 4 in moe_layer, the code would be as follows:
        self._moe_layer = tutel_moe.moe_layer(
            gate_type=_gate_type,
            model_dim=in_features,
            experts={'type': 'ffn',
                     'count_per_node': self.num_local_experts,
                     'hidden_size_per_expert': hidden_features,
                     'activation_fn': lambda x: self._dropout(F.gelu(x))},
            scan_expert_func=lambda name, param: setattr(param, 'skip_allreduce', True),
            seeds=(1, self.dist_rank + 1, self.dist_rank + 1),
            batch_prioritized_routing=use_bpr,
            normalize_gate=normalize_gate,
            is_gshard_loss=is_gshard_loss
        )
    At this point, following Tutel's idea, global_expert_count = num_local_experts * world_size=24, each GPU has 4 experts, and there are a total of 24 experts on 6 GPUs, and all 24 experts are different. The code execution will be stuck in the communicate.py in the tutel source code:
          https://github.com/microsoft/Tutel/blob/main/tutel/impls/communicate.py   
          line 450:     output, f_wait = simple_all_to_all(reshaped_input, group, background=True)
    Perhaps it's because I use pipeline parallelism that the model is split into two parts and placed on two GPUs, but only one GPU can train the layer of the moe, causing communication issues? If I use data parallelism+tutel moe, the code can be executed successfully.

（2）Based on problem 1, I have modified the moe_layer code as follows：
        my_processing_group=tutel.net.create_groups_from_world(group_count=1).data_group
        self._moe_layer = tutel_moe.moe_layer(
            gate_type=_gate_type,
            model_dim=in_features,
            experts={'type': 'ffn',
                     'count_per_node': self.num_local_experts,
                     'hidden_size_per_expert': hidden_features,
                     'activation_fn': lambda x: self._dropout(F.gelu(x))},
            #scan_expert_func=lambda name, param: setattr(param, 'skip_allreduce', True),
            seeds=(1, self.dist_rank + 1, self.dist_rank + 1),
            batch_prioritized_routing=use_bpr,
            normalize_gate=normalize_gate,
            is_gshard_loss=is_gshard_loss,                    
            group=my_processing_group
        )
     I set num_local_experts to 4 in moe_layer，Start training with the same command:
             python -m torch.distributed.launch --nproc_per_node=6 train.py
     and the code can be executed successfully.
     At this point, there are still 4 experts on each GPU,  The model was split into 2 parts and moe_layer is divided into the first part. Therefore,  during the training process, the expert parameters for GPU 0, GPU 1, and GPU 2 have been updated, while the expert parameters for GPU 3, GPU 4, and GPU 5 have not been updated. Due to Deepspeed's all reduce operation on data parallelism, the expert parameters for GPU 0, GPU 1, and GPU 2 are the same, and the expert parameters for GPU 3, GPU 4, and GPU 5 are the same.
     Here, I actually trained a total of 4 experts using Tutel Moe, right?

**Comment by luuck** [comment]
Hello, I am using DeepSpeed to implement data parallelism + pipeline parallelism + tutel moe. My node has 6 GPUs, and I started training with the command: 
                  python -m torch.distributed.launch --nproc_per_node=6 train.py
    The model was split into 2 parts, so the data parallelism is 3 and the model parallelism is 2.
  
(1) If I set num_local_experts to 4 in moe_layer, the code would be as follows:

        self._moe_layer = tutel_moe.moe_layer(
            gate_type=_gate_type,
            model_dim=in_features,
            experts={'type': 'ffn',
                     'count_per_node': self.num_local_experts,
                     'hidden_size_per_expert': hidden_features,
                     'activation_fn': lambda x: self._dropout(F.gelu(x))},
            scan_expert_func=lambda name, param: setattr(param, 'skip_allreduce', True),
            seeds=(1, self.dist_rank + 1, self.dist_rank + 1),
            batch_prioritized_routing=use_bpr,
            normalize_gate=normalize_gate,
            is_gshard_loss=is_gshard_loss
        )

At this point, following Tutel's idea, global_expert_count = num_local_experts * world_size=24, each GPU has 4 experts, and there are a total of 24 experts on 6 GPUs, and all 24 experts are different. The code execution will be stuck in the communicate.py in the tutel source code:
> https://github.com/microsoft/Tutel/blob/main/tutel/impls/communicate.py   
          line 450:     output, f_wait = simple_all_to_all(reshaped_input, group, background=True)

Perhaps it's because I use pipeline parallelism that the model is split into two parts and placed on two GPUs, but only one GPU can train the layer of the moe, causing communication issues? If I use data parallelism+tutel moe, the code can be executed successfully.

(2) Based on problem 1, I have modified the moe_layer code as follows：

        my_processing_group=tutel.net.create_groups_from_world(group_count=1).data_group
        self._moe_layer = tutel_moe.moe_layer(
            gate_type=_gate_type,
            model_dim=in_features,
            experts={'type': 'ffn',
                     'count_per_node': self.num_local_experts,
                     'hidden_size_per_expert': hidden_features,
                     'activation_fn': lambda x: self._dropout(F.gelu(x))},
            #scan_expert_func=lambda name, param: setattr(param, 'skip_allreduce', True),
            seeds=(1, self.dist_rank + 1, self.dist_rank + 1),
            batch_prioritized_routing=use_bpr,
            normalize_gate=normalize_gate,
            is_gshard_loss=is_gshard_loss,                    
            group=my_processing_group
        )

I set num_local_experts to 4 in moe_layer，Start training with the same command:
             python -m torch.distributed.launch --nproc_per_node=6 train.py
and the code can be executed successfully.

  At this point, there are still 4 experts on each GPU,  The model was split into 2 parts and moe_layer is divided into the first part. Therefore,  during the training process, the expert parameters for GPU 0, GPU 1, and GPU 2 have been updated, while the expert parameters for GPU 3, GPU 4, and GPU 5 have not been updated. Due to Deepspeed's all reduce operation on data parallelism, the expert parameters for GPU 0, GPU 1, and GPU 2 are the same, and the expert parameters for GPU 3, GPU 4, and GPU 5 are the same.
   Here, I actually trained a total of 4 experts using Tutel Moe, right?

**Comment by ghostplant** [comment]
> Hello, I am using DeepSpeed to implement data parallelism + pipeline parallelism + tutel moe. My node has 6 GPUs, and I started training with the command: python -m torch.distributed.launch --nproc_per_node=6 train.py The model was split into 2 parts, so the data parallelism is 3 and the model parallelism is 2.
> 
> (1) If I set num_local_experts to 4 in moe_layer, the code would be as follows:
> 
> ```
>     self._moe_layer = tutel_moe.moe_layer(
>         gate_type=_gate_type,
>         model_dim=in_features,
>         experts={'type': 'ffn',
>                  'count_per_node': self.num_local_experts,
>                  'hidden_size_per_expert': hidden_features,
>                  'activation_fn': lambda x: self._dropout(F.gelu(x))},
>         scan_expert_func=lambda name, param: setattr(param, 'skip_allreduce', True),
>         seeds=(1, self.dist_rank + 1, self.dist_rank + 1),
>         batch_prioritized_routing=use_bpr,
>         normalize_gate=normalize_gate,
>         is_gshard_loss=is_gshard_loss
>     )
> ```
> 
> At this point, following Tutel's idea, global_expert_count = num_local_experts * world_size=24, each GPU has 4 experts, and there are a total of 24 experts on 6 GPUs, and all 24 experts are different. The code execution will be stuck in the communicate.py in the tutel source code:
> 
> > https://github.com/microsoft/Tutel/blob/main/tutel/impls/communicate.py
> > line 450:     output, f_wait = simple_all_to_all(reshaped_input, group, background=True)
> 
> Perhaps it's because I use pipeline parallelism that the model is split into two parts and placed on two GPUs, but only one GPU can train the layer of the moe, causing communication issues? If I use data parallelism+tutel moe, the code can be executed successfully.
> 
> (2) Based on problem 1, I have modified the moe_layer code as follows：
> 
> ```
>     my_processing_group=tutel.net.create_groups_from_world(group_count=1).data_group
>     self._moe_layer = tutel_moe.moe_layer(
>         gate_type=_gate_type,
>         model_dim=in_features,
>         experts={'type': 'ffn',
>                  'count_per_node': self.num_local_experts,
>                  'hidden_size_per_expert': hidden_features,
>                  'activation_fn': lambda x: self._dropout(F.gelu(x))},
>         #scan_expert_func=lambda name, param: setattr(param, 'skip_allreduce', True),
>         seeds=(1, self.dist_rank + 1, self.dist_rank + 1),
>         batch_prioritized_routing=use_bpr,
>         normalize_gate=normalize_gate,
>         is_gshard_loss=is_gshard_loss,                    
>         group=my_processing_group
>     )
> ```
> 
> I set num_local_experts to 4 in moe_layer，Start training with the same command: python -m torch.distributed.launch --nproc_per_node=6 train.py and the code can be executed successfully.
> 
> At this point, there are still 4 experts on each GPU, The model was split into 2 parts and moe_layer is divided into the first part. Therefore, during the training process, the expert parameters for GPU 0, GPU 1, and GPU 2 have been updated, while the expert parameters for GPU 3, GPU 4, and GPU 5 have not been updated. Due to Deepspeed's all reduce operation on data parallelism, the expert parameters for GPU 0, GPU 1, and GPU 2 are the same, and the expert parameters for GPU 3, GPU 4, and GPU 5 are the same. Here, I actually trained a total of 4 experts using Tutel Moe, right?

Hi. For case (1), I didn't see any settings related to enable pipeline parallelism but data parallelism of size 3. Do you pipeline parallelism and model parallelism are 2 different concepts. Can you explain the pipeline setting clearly? Anyway, not setting dedicated `group=xxx` is of course not true. For case (2),  if you choose `tutel.net.create_groups_from_world()` to create groups, it could simplify a lot in groups maintaining, however, DeepSpeed's group maintaining will be not useful and even introduce more troubleshooting since you hyrbid 2 different group creation maintainers. I think you should firstly decide which group maintainer to choose while disabling another one.

**Comment by ghostplant** [comment]
@luuck Considering pipeline parallelism is always slow. For your requirement, what's the problem for you not considering "3 data parallelism + 2 expert parallelism"?

**Comment by luuck** [comment]
For case (1), I use the following code to implement pipeline parallelism：

        layer = torch.nn.Sequential(
            model.input_layer,
            model.encoder0,
            model.downsample1,
            model.encoder1,
            model.downsample2,
            model.encoder2,
            model.decoder2,
            model.upsample2,
            model.decoder1,
            model.upsample1,
            model.decoder0,
            model.output_layer
        )
        pipeline_model = PipelineModule(layers=layer, loss_fn=self.criterion, num_stages=2, partition_method="uniform")

        data_set = WeatherData(args, "train")
        ds_config = self.get_ds_config()
        self.model, _, self.data_loader, _ = deepspeed.initialize(
            #args=self.args,
            model=pipeline_model,
            #model_parameters=[p for p in pipeline_model.parameters() if p.requires_grad],
            model_parameters=pipeline_model.parameters(),
            config=ds_config,
            training_data=data_set
        )
In this code，num_stages=2  means that I have split the model into two parts, and moe_lay is placed in encoder2, so it will be divided into the first part.
I started training with the command: python -m torch.distributed.launch --nproc_per_node=6 train.py，the code executed Failed, The 6 GPUs of the node are occupied as follows：

  |    0   N/A  N/A     13353      C   ...iforge3/envs/awakenpy/bin/python3.9       6862MiB |
  |    1   N/A  N/A     13354      C   ...iforge3/envs/awakenpy/bin/python3.9       6862MiB |
  |    2   N/A  N/A     13355	 C   ...iforge3/envs/awakenpy/bin/python3.9       6862MiB |
  |    3   N/A  N/A     13356	 C   ...iforge3/envs/awakenpy/bin/python3.9       8324MiB |
  |    4   N/A  N/A     13357	 C   ...iforge3/envs/awakenpy/bin/python3.9       8324MiB |
  |    5   N/A  N/A     13358	 C   ...iforge3/envs/awakenpy/bin/python3.9       8324MiB |

In this way，The data parallelism is 3, which are GPU 0+GPU 3, GPU 1+GPU 4, GPU 2+GPU 5. The first part with moe_layer of the model is on GPU 0，GPU 1 and GPU 2, while the second part is on GPU 3，GPU 4 and GPU 5. 

If I set  num_stages=1, it means that only use data parallelism+tutel moe, the code can be executed successfully,The 6 GPUs of the node are occupied as follows：

|    0   N/A  N/A     23301      C   ...iforge3/envs/awakenpy/bin/python3.9      12920MiB |
|    1   N/A  N/A     23302      C   ...iforge3/envs/awakenpy/bin/python3.9      12920MiB |
|    2   N/A  N/A     23303	 C   ...iforge3/envs/awakenpy/bin/python3.9      12920MiB |
|    3   N/A  N/A     23304	 C   ...iforge3/envs/awakenpy/bin/python3.9      12920MiB |
|    4   N/A  N/A     23305	 C   ...iforge3/envs/awakenpy/bin/python3.9      12920MiB |
|    5   N/A  N/A     23306      C   ...iforge3/envs/awakenpy/bin/python3.9      12920MiB |
In this way，The data parallelism is 6，There is a whole model on each GPU.

Based on the above analysis, so I said that perhaps it's because I use pipeline parallelism that the model is split into two parts and placed on different GPUs, but only GPU 0，GPU 1 and GPU 2 can train the layer of the moe, causing communication issues?


For case (2), in order to solve the problem，The model size is acceptable so I want each GPU hold the whole parameters of the experts. I don't want a part of experts to each gpu. I just want each GPU to feed different data into the model. Such training mode is similar to the original distributed data parallel of PyTorch. So I choose data parallelism for MoE parameters. I have chosen your following opinion：
https://github.com/microsoft/Tutel/issues/52#issuecomment-1105144317

**Comment by luuck** [comment]
My model cannot fit on a single GPU, so I have to use pipeline parallelism to divide the model into two parts. 
Additionally, I use Deepspeed Zero1, so I choose Choice-2

**Comment by luuck** [comment]
My model cannot fit on a single GPU, so I have to use pipeline parallelism to divide the model into two parts.
Additionally, I use Deepspeed Zero-1 + data parallelism + pipeline parallelism + tutel moe , so I choose Choice-2

**Comment by luuck** [comment]
My model is too large to fit a single GPU, so I have to use pipeline parallelism to divide the model into two parts.
Additionally, I use Deepspeed Zero-1 + data parallelism + pipeline parallelism + tutel moe , so I choose Choice-2

**Comment by ghostplant** [comment]
@luuck Sure, please use this setting when creating moe_layer:

```py
        self._moe_layer = tutel_moe.moe_layer(
            gate_type = {'type': 'top', 'k': top_value, ...},
            experts = {'type': 'ffn', 'count_per_node': 4, 'hidden_size_per_expert': hidden_features, ...},
            model_dim = in_features,
            scan_expert_func = None,
            seeds = (None, None, None),
            group = dist.new_group(ranks=[dist.get_rank()]),
        )
```

Keep in mind the following items:
1. set `scan_expert_func = None` since it will work in tradition data-parallel method, instead of Zero-2/3 method.
2. set `seeds = (None, None, None)` to let its expert parameter initialized and maintained by external framework like Deepspeed.
3. set `group = dist.new_group(ranks=[dist.get_rank()])` so that Tutel Moe layer will internally fallback to legacy data parallel layout.
